In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import sklearn
import category_encoders as ce  # библиотека для кодирования категориальных признаков
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
path1='https://raw.githubusercontent.com/Falirchik/ML/main/diabetic_data.csv'
Y = pd.read_csv(path1)


Y.head(10)#Output our data

C:\Users\nikki\AppData\Local\Temp\ipykernel_16900\3253561709.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  Y = pd.read_csv(path1)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type,discharge_disposition,admission_source,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,NaN,Not Mapped,Physician Referral,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,Emergency,Discharged to home,Emergency Room,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,Emergency,Discharged to home,Emergency Room,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,Emergency,Discharged to home,Emergency Room,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,Emergency,Discharged to home,Emergency Room,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),NaN,Urgent,Discharged to home,Clinic Referral,3,...,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),NaN,Elective,Discharged to home,Clinic Referral,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),NaN,Emergency,Discharged to home,Emergency Room,5,...,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),NaN,Urgent,Discharged to home,Transfer from a hospital,13,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),NaN,Elective,Discharged/transferred to SNF,Transfer from a hospital,12,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [3]:
Y.shape

(101766, 50)

In [4]:
for column in Y.select_dtypes(['object']):
    Y[column] = Y[column].astype('category')
    
Y.dtypes

encounter_id                   int64
patient_nbr                    int64
race                        category
gender                      category
age                         category
weight                      category
admission_type              category
discharge_disposition       category
admission_source            category
time_in_hospital               int64
payer_code                  category
medical_specialty           category
num_lab_procedures             int64
num_procedures                 int64
num_medications                int64
number_outpatient              int64
number_emergency               int64
number_inpatient               int64
diag_1                      category
diag_2                      category
diag_3                      category
number_diagnoses               int64
max_glu_serum               category
A1Cresult                   category
metformin                   category
repaglinide                 category
nateglinide                 category
chlorpropamide              category
glimepiride                 category
acetohexamide               category
glipizide                   category
glyburide                   category
tolbutamide                 category
pioglitazone                category
rosiglitazone               category
acarbose                    category
miglitol                    category
troglitazone                category
tolazamide                  category
examide                     category
citoglipton                 category
insulin                     category
glyburide-metformin         category
glipizide-metformin         category
glimepiride-pioglitazone    category
metformin-rosiglitazone     category
metformin-pioglitazone      category
change                      category
diabetesMed                 category
readmitted                  category
dtype: object

In [5]:
Y['readmitted'].unique()  # число уникальных значений признака readmitted

['NO', '>30', '<30']
Categories (3, object): ['<30', '>30', 'NO']

In [6]:
Y['readmitted'] = Y['readmitted'].replace('<30', 'YES').replace('>30', 'NO')
Y['readmitted'].unique()

['NO', 'YES']
Categories (2, object): ['YES', 'NO']

In [7]:
Y.drop(['patient_nbr', 'encounter_id'], axis=1, inplace=True)
Y.shape

(101766, 48)

In [8]:
Y.describe(include=['category']).T

                           count unique                 top    freq
race                       99493      5           Caucasian   76099
gender                    101766      3              Female   54708
age                       101766     10             [70-80)   26068
weight                      3197      9            [75-100)    1336
admission_type             96475      7           Emergency   53990
discharge_disposition      98075     25  Discharged to home   60234
admission_source           94985     16      Emergency Room   57494
payer_code                 61510     17                  MC   32439
medical_specialty          51817     72    InternalMedicine   14635
diag_1                    101745    716                 428    6862
diag_2                    101408    748                 276    6752
diag_3                    100343    789                 250   11555
max_glu_serum               5346      3                Norm    2597
A1Cresult                  17018      3                  >8    8216
metformin                 101766      4                  No   81778
repaglinide               101766      4                  No  100227
nateglinide               101766      4                  No  101063
chlorpropamide            101766      4                  No  101680
glimepiride               101766      4                  No   96575
acetohexamide             101766      2                  No  101765
glipizide                 101766      4                  No   89080
glyburide                 101766      4                  No   91116
tolbutamide               101766      2                  No  101743
pioglitazone              101766      4                  No   94438
rosiglitazone             101766      4                  No   95401
acarbose                  101766      4                  No  101458
miglitol                  101766      4                  No  101728
troglitazone              101766      2                  No  101763
tolazamide                101766      3                  No  101727
examide                   101766      1                  No  101766
citoglipton               101766      1                  No  101766
insulin                   101766      4                  No   47383
glyburide-metformin       101766      4                  No  101060
glipizide-metformin       101766      2                  No  101753
glimepiride-pioglitazone  101766      2                  No  101765
metformin-rosiglitazone   101766      2                  No  101764
metformin-pioglitazone    101766      2                  No  101765
change                    101766      2                  No   54755
diabetesMed               101766      2                 Yes   78363
readmitted                101766      2                  NO   90409

In [9]:
Y.drop(['examide', 'citoglipton'], axis=1, inplace=True)
Y.shape

(101766, 46)

In [10]:
Y.describe()

,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [11]:
rows_with_invalid_gender = Y[Y['gender'] == 'Unknown/Invalid']  # строки с невалидными значениями признака gender

len(rows_with_invalid_gender)  # число таких строк

3

In [12]:
Y.drop(rows_with_invalid_gender.index, axis=0, inplace=True)  # удаляем из таблицы

len(Y[Y['gender'] == 'Unknown/Invalid'])  # число строк с невалидными значениями признака gender после удаления

0